### ISSUE TITLE
Suggestion to always get the newest version of winget from github

### ISSUE THREAD

**Issue by 1ckov** [asheroto/winget-installer#1]
function getNewestLink($match){
	$uri = "https://api.github.com/repos/microsoft/winget-cli/releases"
	Write-Verbose "[$((Get-Date).TimeofDay)] Getting information from $uri"
	$get = Invoke-RestMethod -uri $uri -Method Get -ErrorAction stop
	Write-Verbose "[$((Get-Date).TimeofDay)] getting latest release"
	$data = $get[0].assets | Where-Object name -Match $match
	return $data.browser_download_url
}

$wingetUrl=getNewestLink("msixbundle")
$wingetLicenseUrl=getNewestLink("License1.xml")

**Comment by asheroto** [comment]
Ooo that's good. I'll add that, thank you. :-)

**Comment by asheroto** [comment]
Thanks again, updated everything and also added your name as an author in the script comments.

FYI - added the script to PSGallery so you don't even have to download the file now, see readme. 😀

Release: https://github.com/asheroto/winget-installer/releases/tag/0.0.3

**Comment by obnys** [comment]
One additional suggestion for this: Would you mind, changing $uri to "https://api.github.com/repos/microsoft/winget-cli/releases/latest" ?
Currently the code (which runs awesome!) installs pre-releases.

**Comment by 1ckov** [comment]
> Thanks again, updated everything and also added your name as an author in the script comments.
> 
> FYI - added the script to PSGallery so you don't even have to download the file now, see readme. 😀
> 
> Release: https://github.com/asheroto/winget-installer/releases/tag/0.0.3

Thank you so much as well, this new trick with the PSGallery, makes life even more easier for my and @obnys'es Project.

**Comment by asheroto** [comment]
Good catch! #2
