### ISSUE TITLE
does not work on server 2019 ( but it should ) 

### ISSUE THREAD

**Issue by TheBigBear** [asheroto/winget-installer#12]
Thank you for this. Great and very helpful. Any idea why it does not work for server 2019 as-is? ( It should .. ) 
BTW the following GIST from @likamrat (Lior Kamrat) does work for server 2019 also. 

https://gist.github.com/likamrat/cae833a6e5b3461709f14c093c21c293

But I don't like his use of the "```https://store.rg-adguard.net/api/GetFiles```" to get some of the downloads ... I thought I post it here in case it helps you figure out why yours does not work on server 2019?

**Comment by asheroto** [comment]
I'm not sure, but I have not had any luck getting it to work on Server 2019 either. It's ideally designed for Windows 11, works with Windows 10 past certain updates. Outside of that scope, even if everything is set up correctly, I can't guarantee it will still work in the future.

This might work for you for now:
https://gist.github.com/likamrat/cae833a6e5b3461709f14c093c21c293?permalink_comment_id=4634351#gistcomment-4634351

I'll circle back to this when I have some more time and see if I can adjust the script at all. Leaving issue open for now.

**Comment by asheroto** [comment]
Hello,

Unfortunately winget is just not compatible with Server 2019. :-/
