### ISSUE TITLE
Switching from winget pre-release to winget stable 

### ISSUE THREAD

**Issue by 1ckov** [asheroto/winget-installer#2]
One additional suggestion for this: Would you mind, changing $uri to "https://api.github.com/repos/microsoft/winget-cli/releases/latest" ?
Currently the code (which runs awesome!) installs pre-releases.

_Originally posted by @obnys in https://github.com/asheroto/winget-installer/issues/1#issuecomment-1172007661_

**Comment by asheroto** [comment]
Ah, good catch! Updated.
