### ISSUE TITLE
Does this work on Server 2019/2022?

### ISSUE THREAD

**Issue by bscheewe** [asheroto/winget-installer#4]
I tried this on Server 2019 and all the steps completed successfully, but winget is not recognized as a command.  I believe Winget should be located at "C:\Program Files\WindowsApps\" but that folder does not exist.  Winget isn't officially supported for Server OSes, but there are workarounds and just want to confirm your script will accommodate the workarounds for servers.

**Comment by daryltucker** [comment]
This works for Windows Server 2022 Datacenter.


PowerShell:
```ps1
Install-Script -Name winget-install
Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
winget-install
```

CMD:
```shell
winget install --id=Microsoft.WindowsTerminal -e
```

**Comment by asheroto** [comment]
> I tried this on Server 2019 and all the steps completed successfully, but winget is not recognized as a command. I believe Winget should be located at "C:\Program Files\WindowsApps" but that folder does not exist. Winget isn't officially supported for Server OSes, but there are workarounds and just want to confirm your script will accommodate the workarounds for servers.

Sorry I just saw this. It should add the correct folder to your PATH environmental variable. You may have to restart on older OS's.

**Comment by daryltucker** [comment]
@asheroto Have you tried Windows Server 2019 Datacenter ?  Even after a reboot...

CMD:

```shell
C:\Windows\system32>winget install --id=Microsoft.WindowsTerminal -e
'winget' is not recognized as an internal or external command,
operable program or batch file.
```

PowerShell:
```ps1
PS C:\Windows\system32> winget install --id=Microsoft.WindowsTerminal -e
winget : The term 'winget' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ winget install --id=Microsoft.WindowsTerminal -e
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (winget:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

This directory is empty in 2019, where 2022 has the executable: `$env:APPDATA\Local\Microsoft\WindowsApps`

**Comment by asheroto** [comment]
I tested it in a new instance of Server 2019 and experienced the same problems. So unfortunately it must not work on Server 2019.

FYI Microsoft Windows Terminal doesn't either. :-/
